"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

#/Users/pawel/Documents/programy/PythonPlay/.venv/lib/python3.9/site-packages/pygame/.dylibs/libopus.0.dylib

from setuptools import setup
import os

data_files = ['libsndfile.dylib','stop.png','play.png','delete.png','pause.png','next.png']

from libs import resources_dirs
#resources_dirs = ['.venv/lib/python3.9/site-packages/_soundfile_data', '.venv/lib/python3.9/site-packages/numpy/.dylibs', '.venv/lib/python3.9/site-packages/pygame/.dylibs', '.venv/lib/python3.9/site-packages/pymediainfo', '.venv/lib/python3.9/site-packages/scipy/.dylibs', '.venv/lib/python3.9/site-packages/tkinterdnd2/tkdnd/osx-x64']


# Rekurencyjne zbieranie plików

for resources_dir in resources_dirs:
    for root, dirs, files in os.walk(resources_dir):
        for file in files:
            full_path = os.path.join(root, file)
            relative_path = os.path.relpath(full_path, resources_dir)
            data_files.append((os.path.dirname(relative_path), [full_path]))

APP = ['milonga.py']
DATA_FILES = data_files
print(data_files)
OPTIONS = {
    'argv_emulation': True,
    'emulate_shell_environment': True,
    'iconfile': 'icon.icns'
}


setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
